/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author Hassan
 */
public class Index extends javax.swing.JFrame {
 public static Map <Integer, Integer> Data_Memory_UserI;
    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        Data_Memory_UserI=new LinkedHashMap<>();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Test1 = new javax.swing.JButton();
        Test2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Test3 = new javax.swing.JButton();
        Test4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        StartingAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssemblyCode = new javax.swing.JTextArea();
        Submit = new javax.swing.JButton();
        Data_Entry = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RISC V SIM");
        setName("Index"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(48, 52, 112));
        jPanel1.setForeground(new java.awt.Color(48, 52, 112));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/10872782.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RISC-V Simulator");

        Test1.setBackground(new java.awt.Color(255, 153, 0));
        Test1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Test1.setForeground(new java.awt.Color(255, 255, 255));
        Test1.setText("Test 1");
        Test1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test1ActionPerformed(evt);
            }
        });

        Test2.setBackground(new java.awt.Color(255, 153, 0));
        Test2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Test2.setForeground(new java.awt.Color(255, 255, 255));
        Test2.setText("Test 2");
        Test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test2ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_________________________________");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tests : ");
        jLabel7.setToolTipText("");

        Test3.setBackground(new java.awt.Color(255, 153, 0));
        Test3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Test3.setForeground(new java.awt.Color(255, 255, 255));
        Test3.setText("Test 3");
        Test3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test3ActionPerformed(evt);
            }
        });

        Test4.setBackground(new java.awt.Color(255, 153, 0));
        Test4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Test4.setForeground(new java.awt.Color(255, 255, 255));
        Test4.setText("Test 4");
        Test4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Test3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Test2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Test1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addComponent(Test4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(Test1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Test2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Test3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Test4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Enter Starting Address :");

        jLabel4.setText("________________________________________________________________________");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Enter RISC-V Assembly Code : ");

        AssemblyCode.setColumns(20);
        AssemblyCode.setRows(5);
        jScrollPane1.setViewportView(AssemblyCode);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Data_Entry.setText("Enter Data");
        Data_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_EntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Data_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartingAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(StartingAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Data_Entry))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
     if(AssemblyCode.getText().isEmpty()){
     JOptionPane.showMessageDialog(this, "Must Enter Assembly Code" , "Empty Field",  JOptionPane.WARNING_MESSAGE);
     }
     else{
        String Assembly_Code = AssemblyCode.getText();
        
        String Starting_AddressTEMP = StartingAddress.getText();
        try{
        int Starting_Address=Integer.parseInt(Starting_AddressTEMP);
        Viewer v = new Viewer(Assembly_Code, Starting_Address, Data_Memory_UserI){}; 
        v.setVisible(true);
        this.dispose();
        }
        catch(NumberFormatException e){
        
         JOptionPane.showMessageDialog(this, "Must Enter Starting Address" , "Empty Starting Address",  JOptionPane.WARNING_MESSAGE);
        
        }
     }
    }//GEN-LAST:event_SubmitActionPerformed

    private void Test1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test1ActionPerformed
        // TODO add your handling code here:
        AssemblyCode.setText("");
        StartingAddress.setText("0");
        AssemblyCode.setText("addi x1, x0, 10"+"\n"+"addi x20, x0, 2000" + "\n"+ "addi x2, x0, 20" + "\n" + "add x3, x2, x1" + "\n"+"sub x4, x1, x2" + "\n" + "sb x1, 0 (x20)" + "\n" + "sh x2, 4 (x20)" + "\n" + "sw x4, 8 (x20)" + "\n" + "lb x10, 8 (x20)" + "\n" + "lh x10, 8 (x20)" + "\n" + "lw x10, 8 (x20)" + "\n" + "lbu x10, 8 (x20)" + "\n" + "lhu x10, 8 (x20)" + "\n" + "slli x11, x1, 2" + "\n" + "srli x12, x1,2" + "\n" + "srai x13, x1, 2");
        
    }//GEN-LAST:event_Test1ActionPerformed

    private void Data_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_EntryActionPerformed
        // TODO add your handling code here:
        
        Data_Entry_GUI DEG = new Data_Entry_GUI();
        DEG.setVisible(true);
    }//GEN-LAST:event_Data_EntryActionPerformed

    private void Test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test2ActionPerformed
        // TODO add your handling code here:

        AssemblyCode.setText("");
        StartingAddress.setText("100");
        AssemblyCode.setText("lui x1,20" + "\n"+ "auipc x2,20"+"\n" + "addi x3,x3,10" + "\n"+ "beq x4,x3,124"+"\n"+ "addi x4,x4,1 "+"\n"+ "jal x5,112"+"\n"+ "addi x6,x6,5"+"\n"+ "addi x7,x7,2"+"\n"+ "blt x6,x7,144"
        +"\n"+ "addi x6,x6,-1" +"\n"+ "jal x8,132" +"\n"+ "addi x9,x9,10"+"\n"+ "addi x10,x10,7"+"\n"+ "bne x9,x10,164"+"\n"+"addi x10,x10,1"+"\n"+"jal x11,152"+"\n"+"addi x12,x12,1"+"\n"+"addi x13,x13,3"+"\n"+"bge x12,x13,184" +"\n"+"addi x12,x12,1"+"\n"+"jal x14,172"+"\n"+"addi x15,x15,5"+"\n"+"addi x16,x16,2"+"\n"+"bltu x15,x16,204"+"\n"+"addi x15,x15,-1"+"\n"+"jal x18,192"+"\n"+"addi x19,x19,1"+"\n"+"addi x20,x20,3"+"\n"+"bgeu x19,x20,224"+"\n"+"addi x19,x19,1"+"\n"+"jal x21,212"+"\n"+"ECALL"); //Needs to be reworked
        
    }//GEN-LAST:event_Test2ActionPerformed

    private void Test3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test3ActionPerformed
        // TODO add your handling code here:
        AssemblyCode.setText("");
        StartingAddress.setText("0");
        AssemblyCode.setText("addi x1, x0, 1" + "\n" + "addi x2, x0, 2" + "\n" + "addi x3, x0, -5" + "\n" + "addi x4, x0, 2" + "\n" + "slti x10, x1, 5" + "\n" + "slti x10, x1, -5" + "\n" + "sltiu x11, x1, 5" + "\n" + "sltiu x11, x1, -5" + "\n" + "slt x12,x1, x3" + "\n" + "slt x12, x1, x2" + "\n" + "sltu x13, x1, x3" + "\n" + "sltu x13, x1, x2 " + "\n" + "sll x14,x2,x4"+"\n"+"EBREAK");
    }//GEN-LAST:event_Test3ActionPerformed

    private void Test4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test4ActionPerformed
        // TODO add your handling code here:
        AssemblyCode.setText("");
        StartingAddress.setText("0");
        AssemblyCode.setText("addi x1, x0, 20" + "\n" + "addi x2, x0, 30" + "\n" + "addi x3, x0, 2" + "\n" + "xori x10, x1, 12" + "\n" + "ori x11, x1, 12" + "\n" + "andi x12, x1, 12"+ "\n" + "xor x13, x1, x2" + "\n" + "or x14, x1, x2" + "\n" + "and x15, x1, x2" + "\n" + "srl x16, x2, x3" + "\n" + "sra x17, x2, x3"+"\n"+"FENCE");
    }//GEN-LAST:event_Test4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AssemblyCode;
    private javax.swing.JButton Data_Entry;
    private javax.swing.JTextField StartingAddress;
    private javax.swing.JButton Submit;
    private javax.swing.JButton Test1;
    private javax.swing.JButton Test2;
    private javax.swing.JButton Test3;
    private javax.swing.JButton Test4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
